(ns clj.generate.ns
  (:require [clj.new.templates :as tmpl]
            [clj.generate.file :as gen-file]))

(defn generate
  "Generate a new namespace relative to the prefix."
  [prefix ns-name]
  (gen-file/generate prefix ns-name (str "(ns " ns-name "\n  \"Generated by clj\")\n")))
